//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.20 at 11:38:34 AM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.technolyne.com/film", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.technolyne.springsoap.model;
